name: Python CI/CD Pipeline  # 流程名称

on:  # 定义触发事件
  push:  # 在推送时触发
    branches:
      - main  # 只对 main 分支

jobs:
  remote-build-and-deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 的运行环境

    steps:
    - name: Remote Operations
      uses: appleboy/ssh-action@master
      with:
        host: your-server.com
        username: server_user
        key: ${{ secrets.SSH_KEY }}
        script: |
          # 确保 git 安装在服务器上
          git clone https://github.com/sweetlunar233/PaperWingsCarryingQuestions_Basic.git || git -C PaperWingsCarryingQuestions_Basic pull
          cd PaperWingsCarryingQuestions_Basic

          # 设置 Node.js 环境
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # 设置 Python 环境
          sudo apt-get update
          sudo apt-get install -y python3.11 python3-pip

          # 构建 Docker 镜像
          docker-compose up --build -d

          # 进入后端项目目录，安装依赖并运行测试
          cd Questionnaire_backend/backend
          python3.11 manage.py test
          
