name: Python CI/CD Pipeline  # 流程名称

on:  # 定义触发事件
  push:  # 在推送时触发
    branches:
      - main  # 只对 main 分支

jobs:
  remote-build-and-deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 的运行环境

    steps:
    - name: Remote Operations
      uses: appleboy/ssh-action@master
      with:
        host: 49.232.201.229
        username: ubuntu
        password: BUaa21374125
        key: ${{ secrets.SSH_KEY }}
        script: |
          # 检查并安装 git
          if ! command -v git &> /dev/null; then
            echo "Git not found. Installing Git..."
            sudo apt-get update
            sudo apt-get install -y git
          fi
          
          if [ -d "PaperWingsCarryingQuestions_Basic" ]; then
              # 如果项目目录存在，则进入目录并执行 git pull
              cd PaperWingsCarryingQuestions_Basic
              git pull
            else
              # 如果项目目录不存在，则执行 git clone
              git clone https://github.com/sweetlunar233/PaperWingsCarryingQuestions_Basic.git
              cd PaperWingsCarryingQuestions_Basic
            fi

          # 构建 Docker 镜像
          docker-compose up --build

          # 进入后端项目目录，安装依赖并运行测试
          cd Questionnaire_backend/backend
          python3.11 manage.py test

