name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  remote-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}

      - name: Install Updates and Basic Tools
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v git &> /dev/null; then
              echo "Git not found. Installing Git..."
              sudo apt-get update
              sudo apt-get install -y git
            fi

      - name: Install Docker
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

      - name: Install Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! docker compose version &> /dev/null; then
              echo "docker-compose-plugin not found. Installing docker-compose-plugin..."
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
              sudo apt  install docker-compose 
            fi

      # - name: Install Python 3.11
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 82.156.97.95
      #     username: ubuntu
      #     password: BUaa2221
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       if ! command -v python3.11 &> /dev/null; then
      #         echo "Python 3.11 not found. Installing Python 3.11..."
      #         sudo apt-get install -y -o Acquire::http::Proxy="http://mirrors.aliyun.com/ubuntu/" python3.11 python3.11-venv python3.11-dev ---fix-missing true
      #       fi

      - name: Prepare Application Environment
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            # echo "--------------------------------------------------------------6666666"
            # echo "$(python3 --version)"

            if [ -d "PaperWingsCarryingQuestions_Basic" ]; then
              cd PaperWingsCarryingQuestions_Basic
              git pull
              cd ..
            else
              git clone https://github.com/sweetlunar233/PaperWingsCarryingQuestions_Basic.git
            fi

            cd PaperWingsCarryingQuestions_Basic
            cd Questionnaire
            sudo npm install
            sudo npm run build
            cd ..
            # sudo docker builder prune -a -f 
            
            sudo docker-compose up --build



            # # 运行docker-compose构建并在后台运行
            # sudo docker-compose up --build -d

            # # 等待指定容器的状态达到 'Up'
            # while true; do
            #   # 获取正在运行的容器状态
            #   running_containers=$(sudo docker ps --filter "status=running" --format "{{.Names}}")
              
            #   # 检查指定容器是否都在运行
            #   if [[ $(echo "$running_containers" | grep -E 'mydb|myback|myfront' | wc -l) -eq 3 ]]; then
            #       break
            #   fi

            #   echo "wait 5"
            #   echo "$(sudo docker ps --filter "status=running" --format "{{.Names}}")"
            #   sleep 5
            # done



            echo "--------------------------------------------------docker-compose finish"
            

      - name: python manage.py test
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.97.95
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "--------------------------------------------------------------6666666"
            echo "$(ls)"
            echo "--------------------------------------------------------------6666666"
            cd PaperWingsCarryingQuestions_Basic
            cd Questionnaire_backend
            cd backend
            sudo docker exec myback python3 manage.py test
