name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  remote-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}

      - name: Install Updates and Basic Tools
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v git &> /dev/null; then
              echo "Git not found. Installing Git..."
              sudo apt-get update
              sudo apt-get install -y git
            fi

      - name: Install Docker
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

      - name: Install Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! docker compose version &> /dev/null; then
              echo "docker-compose-plugin not found. Installing docker-compose-plugin..."
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            fi

      - name: Install Python 3.11
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v python3.11 &> /dev/null; then
              echo "Python 3.11 not found. Installing Python 3.11..."
              sudo apt-get install -y software-properties-common
              sudo add-apt-repository ppa:deadsnakes/ppa
              sudo apt-get install -y python3.11 python3.11-venv python3.11-dev
            fi

      - name: Prepare Application Environment
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.201.229
          username: ubuntu
          password: BUaa21374125
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -d "PaperWingsCarryingQuestions_Basic" ]; then
              cd PaperWingsCarryingQuestions_Basic
              git pull
            else
              git clone https://github.com/sweetlunar233/PaperWingsCarryingQuestions_Basic.git
              cd PaperWingsCarryingQuestions_Basic
            fi
            sudo docker compose up --build
            
            docker exec -it my_backend python manage.py test

